language: python
python:
- '3.6'
sudo: false
branches:
  only:
  - master
install:
- pip install -r requirements.txt
jobs:
  include:
  - stage: Build Docker
    script: "./travis_scripts/docker-build.sh"
    if: "(NOT type IN (pull_request)) AND ((branch = master) OR (tag IS present))"
env:
  global:
  - secure: jZQSq6M588j9dQDP7kV6qH7Sln03IOssE0TbSTsFLLx5xO2ErndaVVYhnwvHRGylfmAlubUPtLq7pKpIycQk1HzVLZrgZA89ydZEj8vLfCkNcJlEW2nAPzsInd/LJkxyiRtgSAfMG6JT+RT2eGko81LC227ejwmwJ5ZmU+Sx8836KiEurLIHUBUAdMPAxctPNI454CfKFmK8GI+MYtY8lWiyi/LfOE4KkRwkZww3e2cBWWPsBKgC0NkILyDXBqhVcHqOxVqPRTSNAPycuNSR07XZR7H4yquSVztYT2kpIgp4o5/E6eh5mcVAOCJhWKwLrYRUznQZiKiMRrIBxKLyTupo/pGLKn5Tlo30XwoaZtzHO9PZVBVE7BgJpdt4wbTr7hpeFeqbgrdeX/6n3ALYZOZ7rsQ5tS2gVb6y+RDXtIr0JFfNiDNaq4afkatmIQSPsU3/I3vGAGXVRvfTrbofSzua+ralnWai7spWtHZZQDc1fls0CDvFcLrPCI3NTEIdQRHfSzOa9bImDSRdo39C/Wu6G5ZqP013geqTg+UNjNecvbXE+NmEeitcx/oDLIRyGkmPWqUyDDz2z5UVVauEYio2JVbzhx8wP5mhyx8TwzqfvCsV7LlTVMjEvmtRiFFdiJNhSKdk1ORLg006v5DDlymx3BNBKagHwioVqY1I49Y=
  - secure: djKglwedBXiD492ycw3sRC3vntdpqoiSDmuoz0Dh7KEftxh5dpN3DfXzRVT1THi5i0Bn8ryBAxQftIWEvXLAmXAxWIjY+M1amzCztnOlSpKUMMbe1jJ4hEhj55YQ6XLI4INdf1KSqNTbU21eT/cdqEsShLEg/5uSlBnBaJ3wF5kIsF+YWogSWTCrK/5/XIUzeC4M443MQvTVlZue8XGDVY5jIceh/pe7zj46rBn3SgtR+cHch6HIbRka3MvD58gL3ysRZaHHg9JdcbaovLVL5zHaD3iRolEfiRoUSFPsA5ofMb7WFNoYUzWwLAwCS7p2HwnIFohDY3b4p/wdc1zbW/Hl27MoZemMK4GXclXRbhC5RKxBJuRWNXBr56C8fUTnSkDclY9kqyukxsIcWGEag4y6cDLFOPekLRMQBHKGGmppoULwVXEkGtoPITadpQ0cwhCKsWuIE0KMYlEGW8QJachxdqOYngt9/VFVfRveTUeNm04KJVPOmQ7x2+yTstB3FAIPmbw21T4KSs0boBZ7+WtkprDVI2NrPCWUl3ykBcwkfog+VOq/t0tk1YKgNS7oCK7gei6IbHBEA2Z2vfxjmA6l8Lj4tBWehHrVkT9cCvZCUoL2xOIwvMfe6eC3nRksZF0ENekg8VghDvBo6XCKaaAPlrEL8mB1UkNOYv6iQrE=
